name: Check code

on:
  pull_request:
    branches:
    - main

jobs:
  check_code_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check code formatting with eslint
      run: npm run lint
